apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app.kubernetes.io/name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: web-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web-server
        date: "{{ now | unixEpoch }}"  # replace :latest with :commit-sha in CI build process
    spec:
      containers:
        - name: nginx
          image: {{ .Values.image.repository }}/{{.Chart.Name}}/nginx
          ports:
            - containerPort: 8080
