services:
  nginx:
    extends:
      file: common-services.yaml
      service: nginx
    container_name: ${PROJECT_NAME:-symfony-react-skeleton}_nginx
    build:
      target: base
    image: ${PROJECT_NAME:-symfony-react-skeleton}_nginx:1.25-alpine
    ports:
      - "81:8080"
    volumes:
      - ../fe/dist:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  php:
    extends:
      file: common-services.yaml
      service: php
    container_name: ${PROJECT_NAME:-symfony-react-skeleton}_php
    build:
      target: local
      args:
        - symfony_mode=dev
    image: ${PROJECT_NAME:-symfony-react-skeleton}_php:8.4-fpm-alpine
    volumes:
      - ../api:/var/www/html

  postgres:
    container_name: ${PROJECT_NAME:-symfony-react-skeleton}_postgres
    image: postgres:${DATABASE_SERVER_VERSION:-16}-alpine
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-app}
      POSTGRES_USER: ${DATABASE_USER:-app}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "${DATABASE_NAME:-app}", "-U", "${DATABASE_USER:-app}" ]
      timeout: 5s
      retries: 5
      start_period: 60s
    ports:
      - ${DATABASE_PORT:-5432}
    networks:
      - backend

networks:
  public:
    name: ${PROJECT_NAME:-symfony-react-skeleton}_public
  backend:
    name: ${PROJECT_NAME:-symfony-react-skeleton}_backend

volumes:
  database_data:
    name: ${PROJECT_NAME:-symfony-react-skeleton}_postgresql-data
