apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: nginx-service
      port:
        number: 8080
  rules:
    - host: "*.bungo.cz"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 8080

#  rules:
#    - host: www.example.com
#      http:
#        paths:
#          - pathType: Prefix
#            backend:
#              service:
#                name: exampleService
#                port:
#                  number: 80
#            path: /
#  tls:
#    - hosts:
#        - www.example.com
#      secretName: example-tls

#apiVersion: v1
#kind: Secret
#metadata:
#  name: example-tls
#  namespace: foo
#data:
#  tls.crt: <base64 encoded cert>
#  tls.key: <base64 encoded key>
#type: kubernetes.io/tls
