# Declare variables to be passed into your templates.


# Don't hardcode namespace variable here, use "helm * --namespace {your_namespace}" instead
# namespace: symfony-react-skeleton-prod

image:
  repository: europe-central2-docker.pkg.dev/basic-388908/totea-symfony-react-skeleton-ar

# Use terraform output "app_gcp_service_account_name" from infrastructure repo.
# Or if you use your own infrastructure, use cloud provider service account identifier.
app_gcp_service_account_name: skeleton-prod-gke-workload@basic-388908.iam.gserviceaccount.com

# Use terraform output "app_k8_service_account_name" from infrastructure repo.
# Or if you use your own infrastructure, use k8 serviceAccount name which is known to cloud provider service account.
app_k8_service_account_name: gcp-secret-manager-binding-service-account

# Nginx ingress controller will route all request from {host} to your nginx service. If you want to test url with IP only, provide host header "anything.example.com"
host: "*.example.com"
