# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    application_name: 'skeleton'
    placeholder: "**placeholder**"
    env(DATABASE_HOST_RESOLVED): '%env(DATABASE_HOST)%'
    env(DATABASE_USER_RESOLVED): '%env(DATABASE_USER)%'
    env(DATABASE_PASSWORD_RESOLVED): '%env(DATABASE_PASSWORD)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/App/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/App/'

    Context\:
        resource: '../src/Context/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Controller\StatusController:
        arguments:
            $appName: '%application_name%'
            $environmentName: '%env(string:default:placeholder:ENVIRONMENT_NAME)%'

    Monolog\Formatter\GoogleCloudLoggingFormatter:
